### ISSUE TITLE
Error with inproc

### ISSUE THREAD

**Issue by ncastrog** [ManyDesigns/Portofino#12]
Hello I found an error when connecting to a postgresql database 10.2 referencing and indproc column that does not exist since postgresql 7.3.

If you follow the wizard it gives the error on the query:

SELECT 
NULL AS TABLE_CAT, 
NULL AS TABLE_SCHEM,  
ct.relname AS TABLE_NAME, 
NOT i.indisunique AS NON_UNIQUE, 
NULL AS INDEX_QUALIFIER, 
ci.relname AS INDEX_NAME,  
CASE 
    i.indisclustered  WHEN true THEN 1 
    ELSE 
        CASE 
            am.amname  WHEN 'hash' THEN 2 
            ELSE 3 
        END  
            END AS TYPE,  
a.attnum AS ORDINAL_POSITION,  
CASE 
    **i.indproc WHEN 0** 
        THEN a.attname 
        ELSE ip.proname || '(' || ai.attname || ')' 
END AS COLUMN_NAME, 
NULL AS ASC_OR_DESC,  
ci.reltuples AS CARDINALITY,  
ci.relpages AS PAGES, 
NULL AS FILTER_CONDITION  
FROM 
pg_class ct, pg_class ci, pg_attribute a, pg_am am, pg_attribute ai, pg_index i 
LEFT JOIN pg_proc ip 
ON (i.indproc = ip.oid)  WHERE ct.oid=i.indrelid 
AND ci.oid=i.indexrelid 
AND a.attrelid=ci.oid 
AND ci.relam=am.oid  
AND ai.attnum = i.indkey[0] 
AND ai.attrelid = ct.oid  
AND ct.relname = 'sql_sizing_profiles' ORDER BY NON_UNIQUE, 
TYPE, 
INDEX_NAME, 
ORDINAL_POSITION

**Comment by alessiostalla** [comment]
Closing because it's old and unanswered.
