### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [ManyDesigns/Portofino#174]
Hi
The following lines have cryptographic API misuses. <br> File name => dispatcher/src/main/java/com/manydesigns/portofino/dispatcher/security/jwt/JWTRealm.java: Line number => 54: API name => SecretKeySpec:<BR> File name => dispatcher/src/main/java/com/manydesigns/portofino/dispatcher/security/jwt/JWTRealm.java: Line number => 54: API name => SecretKeySpec:<BR>

**Comment by alessiostalla** [comment]
Checked those & everything seems to be in order.
This looks like a wild bot signaling bogus stuff (see e.g. https://github.com/mob41/broadlink-java-api/issues/22).
