### ISSUE TITLE
JavaClassAccessor probably not threadsafe

### ISSUE THREAD

**Issue by mbettiol** [ManyDesigns/Portofino#3]
I was just exploring the framework and saw this in 
[`com.manydesigns.elements.reflection.JavaClassAccessor`](https://github.com/ManyDesigns/Portofino/blob/master/elements/src/main/java/com/manydesigns/elements/reflection/JavaClassAccessor.java)

`static {
        classAccessorCache = new HashMap<Class, JavaClassAccessor>();
    }`

```
public static JavaClassAccessor getClassAccessor(Class javaClass) {
        JavaClassAccessor cachedResult = classAccessorCache.get(javaClass);
        if (cachedResult == null) {
            logger.debug("Cache miss for: {}", javaClass);
            cachedResult = new JavaClassAccessor(javaClass);
            logger.debug("Caching key: {} - Value: {}",
                    javaClass, cachedResult);
            classAccessorCache.put(javaClass, cachedResult);
        } else {
            logger.debug("Cache hit for: {} - Value: {}",
                    javaClass, cachedResult);
        }
        return cachedResult;
    }
```

since `classAccessorCache` is just an HashMap and you are lazy loading classes into the map some sort of synchronization should be used (e.g.:  ConcurrentHashMap or double lock) to prevent `classAccessorCache` corruption

Hope it helped

**Comment by alessiostalla** [comment]
Closed with commit https://github.com/ManyDesigns/Portofino/commit/60b8f0d5a631f341c11c7bd910f2387671869a79
