### ISSUE TITLE
:configuration non mostra se un attributo è required

### ISSUE THREAD

**Issue by mitto98** [ManyDesigns/Portofino#393]
Nella risposta di :configuration sotto 'properties' non c’è l’informazione se l’attributo è required o meno.
Sarebbe utile avere il campo isRequired direttamente in :configuration in modo da non dover fare una chiamata a :classAccessor solo per ottenere questa informazione.

**Comment by alessiostalla** [comment]
In realtà è il classAccessor del crud che fa fede per quanto riguarda required e tutte le altre annotation. La configurazione non ha modo di sapere quelle informazioni. Effettivamente, nel crud la configurazione serve solo in fase di configurazione della pagina, ma Portofino la richiede per tutte le pagine sempre, forse si potrebbe risparmiare una chiamata aggiungendo un flag (tipo "configurationNeededOnlyInSettingsPanel"), ma non credo abbia un impatto così significativo da giustificare una logica più complicata (e una cosa in più che deve sapere chi estende le pagine o ne crea di nuove).

**Comment by mitto98** [comment]
Questa issue è nata da una discussione su slack, te la incollo per darti il contesto

> Mattia
> Ciao, ho un dubbio sugli endpoint che Portofino fornisce di base sulle crud actions, che differenza c’è, a parte la struttura, tra i dati che mi ritorna :classAccessor e :configuration riguardo alle informazioni sugli attributi dell’entità?
L’unica differenza che noto è che su :configuration non c’è l’informazione se l’attributo è required o meno. C’è una motivazione per cui non è presente o è solo una mancanza?
>
> @milo-donati 
> non saprei così a pelle sinceramente.possibile che il configuration sia relativo alla singola configurazione della pagina mentre il classaccessor sia la descrizione dell'entità (e quindi del model)
>
> @Angelo-Lupo 
> Mattia sulla motivo per cui non ci sia confermo che sia una mancanza (da fixare). La differenza tra :classAccessor e :configuration è quella indicata da Milo.


Al momento sto sviluppando su un frontend non basato su quello di default e sto cercando di generare dinamicamente il form di creazione e modifica basandomi sui dati che ricevo dalla configuration. Per ottenere tutti i dati che mi servono sono obbligato a richiedere la configuration, il selectionProvider solo per associare i nomi chiavi esterne ai relativi attributi e il classAccessor solo per vedere se il campo è required o meno.

Dato che il configuration include comunque quasi tutte queste informazioni mi chiedevo se fosse possibile aggiungere questi due campi alla configuration in modo da evitare due chiamate in più per ogni pagina caricata.
Secondo me semplificherebbe di molto l'uso di questi endpoint, ovviamente se la cosa rubasse più di 5 minuti o dovesse comportare "breaking changes", non è un problema e lascio le tre chiamate al backend.

**Comment by alessiostalla** [comment]
La /:configuration la puoi ignorare, perché non definisce da sola la
configurazione reale del crud, che è ottenuta incrociando la
/:configuration con il model.
Al momento le chiamate che devi fare sono due: /:classAccessor e
/:selectionProvider. Queste ti danno la configurazione effettiva [*]. Si
potrebbe implementare un'unica chiamata che le accorpa in modo da ridurre
le richieste, ma farlo bene non è banale perché i due metodi serializzano
in JSON usando meccanismi diversi per ragioni storiche quindi bisognerebbe
trovare il modo di uniformarli.

[*] ad essere precisi, la reale configurazione effettiva sta nel form (di
Elements), ma non c'è un metodo per restituirlo via REST. Comunque, il form
può differire da classAccessor e selectionProvider solo se modificato
programmaticamente via Groovy, per cui in tal caso potresti fare custom sia
backend che frontend.

**Comment by mitto98** [comment]
Ho capito, grazie per il chiarimento.
Rimuovo la chiamata a /:configuration ed elaboro i dati che mi forniscono /:classAccessor e /:selectionProvider.

Grazie 👍
