### ISSUE TITLE
Validation issues during insertion float/double numbers

### ISSUE THREAD

**Issue by mattiantonini** [ManyDesigns/Portofino#471]
- Version: Portofino 5.*
- DB: PostgreSQL 12

When you create a page (CRUD) with a numeric field (float/double), it automatically limits the values in (-1; +1). Using annotation over the table associate with the page, it is possible to extend the limits, however, only the upper limit works properly. If the lower limit is set, the page is not able to process the data (the button create/edit is not activated).

Moreover, the DB renders float/double numbers with dots (.) to separate the integer part from the decimal part. Portofino UI requires that the numbers be inserted with commas (,) to separate the parts.

I think the main bug is in the UI component based on Angular and how it manages the validation of the fields.

To replicate the problem:
1. SQL code of the table
```sql
CREATE SEQUENCE public.mytable_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

CREATE TABLE "public"."mytable" (
    "id" integer DEFAULT nextval('my_table_id_seq') NOT NULL,
    "value" double precision NOT NULL,
    CONSTRAINT "mytable_id" PRIMARY KEY ("id")
) WITH (oids = false);
```
2. Import in Portofino model, and try to impose the max (e.g., 10000000) and min (e.g. -1000000) values in the Up-stairs section.
3. Create a page to insert/edit the table.
4. Try to insert double values. There are validation problems in inserting the data.

Let me know if you need additional info!

**Comment by alessiostalla** [comment]
Sorry for coming to this after such a long time. I need to verify this, but for the following part I have an insight:
> Portofino UI requires that the numbers be inserted with commas (,) to separate the parts.

This, I think, comes from the language of the browser. If you have your browser asking for pages in Italian as the first choice, Portofino will select the Italian locale, which uses the comma to separate integer digits from decimal digits.
Now, if you want to enforce using the English locale always, I think there's a way to do it, but I have to research it – and then add it to the [cookbook](https://github.com/ManyDesigns/Portofino/wiki/Cookbook).

**Comment by alessiostalla** [comment]
Please see https://youtu.be/kRct1vJP-s0 for a video explanation of this bug & the adopted solution.
