### ISSUE TITLE
5.3.0 Permissions disappeared

### ISSUE THREAD

**Issue by jkcv** [ManyDesigns/Portofino#476]
On Portofino 5.3.0, Upstairs-Permissions there is nothing, but the Save and Cancel buttons. 

The page looks like this:

-------------------------------------------------------------------------------------------
Welcome navigate_next --> Upstairs navigate_next --> Permissions

 

Save <- Cancel

-------------------------------------------------------------------------------------------

Portofino 5.3.0 running on Debian 9.12 Stretch

**Comment by alessiostalla** [comment]
I see them as expected. Do you have any errors in the developer console in your browser?

**Comment by alessiostalla** [comment]
I'm closing because I couldn't reproduce this, feel free to reopen if you have additional information
