### ISSUE TITLE
Could not find artifact com.manydesigns:portofino-spring-boot:jar:5.3.2-SNAPSHOT 

### ISSUE THREAD

**Issue by primillet** [ManyDesigns/Portofino#531]
Following https://github.com/ManyDesigns/Portofino/wiki/Building-from-source to build from source, I got the following error:

[ERROR] Failed to execute goal on project portofino-security-shiro: Could not resolve dependencies for project com.manydesigns:portofino-security-shiro:jar:5.3.2-SNAPSHOT: Could not find artifact com.manydesigns:portofino-spring-boot:jar:5.3.2-SNAPSHOT -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal on project portofino-security-shiro: Could not resolve dependencies for project com.manydesigns:portofino-security-shiro:jar:5.3.2-SNAPSHOT: Could not find artifact com.manydesigns:portofino-spring-boot:jar:5.3.2-SNAPSHOT

Steps I took:
1 git clone https://github.com/ManyDesigns/Portofino.git portofino
2. cd portofino
3. mvn install

I am using Visual Studio Code, and running OpenJDK 11 on Ubuntu 20.04.

Please help. thanks

**Comment by alessiostalla** [comment]
Hi, when building from source from a development branch, you can expect
breakage. Only tagged versions are guaranteed to build cleanly. In your
case, this is a minor issue that we're aware of, but haven't yet got around
to fix.

Il gio 17 mar 2022, 23:42 primillet ***@***.***> ha scritto:

**Comment by primillet** [comment]
Thank you for your reply.
I used a tag version v5.3.1 to build and got it done:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:02 min
[INFO] Finished at: 2022-03-18T20:42:16+08:00
[INFO] ------------------------------------------------------------------------

with some errors about Angular at the end of the build:
[ERROR] - Generating browser application bundles (phase: setup)...
[ERROR] Compiling @angular/cdk/keycodes : es2015 as esm2015
[ERROR] Compiling @angular/core : es2015 as esm2015
[ERROR] Compiling @angular/animations : es2015 as esm2015
....
[ERROR] Compiling @angular/material/grid-list : es2015 as esm2015
[ERROR] ✔ Browser application bundle generation complete.
[ERROR] ✔ Browser application bundle generation complete.
[ERROR] - Generating ES5 bundles for differential loading...
[ERROR] ✔ ES5 bundle generation complete.
[ERROR] - Copying assets...
[ERROR] ✔ Copying assets complete.
[ERROR] - Generating index html...
[ERROR] ✔ Index html generation complete.
[ERROR] - Generating service worker...
[ERROR] ✔ Service worker generation complete.

**Comment by alessiostalla** [comment]
That's unfortunately normal as, for some reason, the Angular build writes some of its messages on standard error.
