### ISSUE TITLE
Archetype: rewrite rule for Angular routes (they must be redirected to /)

### ISSUE THREAD

**Issue by alessiostalla** [ManyDesigns/Portofino#67]

**Comment by Ema90** [comment]
I've used 
`RewriteRule ^(\/(?!api|portofino|.*.js|.*.css|.*.woff|.*.woff2|.*.svg|.*.json|.*.png|.*.jpg|.*.ttf|.*.eot).*)$ /index.jsp [L]`

in WEB-INF/rewrite.config
