### ISSUE TITLE
CRUD page error 404

### ISSUE THREAD

**Issue by dan-aksenov** [ManyDesigns/Portofino#8]
Got error 404 (The requested resource is not available) while trying to access newly created CRUD page.
Also unable to browse tables from Administration.tables menu. Creating Chart web page went fine.
Using portofino 4.2.2(from Sourceforge) and Postgresql 9.5.

**Comment by Ema90** [comment]
Can you please paste here detailed error exceptions from Catalina log?

Portofino 4.2.2 is distributed with postgresql-9.3 jdbc4 driver , you can try to download specific driver for Postgres 9.5 .

**Comment by dan-aksenov** [comment]
10-Oct-2016 15:01:25.935 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for se
rvlet [default] in context with path [] threw exception [ActionBean execution threw an exception.] with root cause
 java.lang.Error: No setup exists for database: my_finance

**Comment by dan-aksenov** [comment]
..from catalina.out

> 2016-10-10 15:03:02,000 WARN  c.m.p.pageactions.crud.CrudAction          Crud null (/welcome/crud) has an invalid database: null


..from localhost.2016-10-10.log
> 10-Oct-2016 15:01:25.935 SEVERE [http-nio-8080-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for se
> rvlet [default] in context with path [] threw exception [ActionBean execution threw an exception.] with root cause
>  java.lang.Error: No setup exists for database: my_database

**Comment by dan-aksenov** [comment]
pushed "close" by mistake.
correct me if I wrong. there's no pg-95 jdbc yet.

**Comment by Ema90** [comment]
You're right .

"No setup exists for database: my_database" means that it's impossible to connect to the DB , is login working? 

Can you check in Administration/Connection Providers section the connection status for "my_database" ?

**Comment by dan-aksenov** [comment]
Is says "connected" in green colour :)
But when I try to browse tables, it holds for a second, then showes nothing.
Also as I mentioned already: I have another page (chart), which displays correct data.
May be theres some difference whith pure sql (in chart) and HQL (in CRUD)?

**Comment by Ema90** [comment]
Please , try to click on Synchronize button in Connection provider detail page .

**Comment by dan-aksenov** [comment]
> Connection provider synchronized correctly.
but still no list tables nor crud page

**Comment by Ema90** [comment]
Can you continue this discussion on our mailing list? 

[http://groups.google.com/group/manydesigns-portofino](url)

**Comment by dan-aksenov** [comment]
done.
https://groups.google.com/forum/#!topic/manydesigns-portofino/02dZK6W-2pQ

**Comment by dan-aksenov** [comment]
Table needed PK to function propertly.
