### ISSUE TITLE
Problem with standalone version

### ISSUE THREAD

**Issue by mesirendon** [ManyDesigns/Portofino#9]
I downloaded the zip from sourceforge and ran the upstart.sh but I'm getting this error
![screenshot_20170302_120747](https://cloud.githubusercontent.com/assets/1184373/23518321/1b647e60-ff41-11e6-9ba9-decef27d3d72.png)

**Comment by alessiostalla** [comment]
Hi, thanks for the report. See https://groups.google.com/d/msg/manydesigns-portofino/FjwqkXJ3Smk/vbfSEifiAAAJ
